# This reformats the Rails to follow the Rubocop cop basic standard, it's there because StandardRB
# still isn't perfect.

AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
